<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WKWIN1512713" ignored="4" name="Regression 2" tests="6" failures="1" timestamp="14 Feb 2019 15:25:29 GMT" time="0.061" errors="0">
  <testcase name="dataProviderTest" time="0.008" classname="testexercise.testng1"/>
  <testcase name="dataProviderTest" time="0.004" classname="testexercise.testng1"/>
  <testcase name="dataProviderTest" time="0.002" classname="testexercise.testng1"/>
  <testcase name="regression1" time="0.001" classname="testexercise.testng1"/>
  <testcase name="regression2" time="0.003" classname="testexercise.testng1"/>
  <testcase name="regression3" time="0.005" classname="testexercise.testng1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testexercise.testng1.regression3(testng1.java:34)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- regression3 -->
  <testcase name="demo1" time="0.0" classname="testexercise.testng1">
    <ignored/>
  </testcase> <!-- demo1 -->
  <testcase name="smoke1" time="0.0" classname="testexercise.testng1">
    <ignored/>
  </testcase> <!-- smoke1 -->
  <testcase name="demo3" time="0.0" classname="testexercise.testng1">
    <ignored/>
  </testcase> <!-- demo3 -->
  <testcase name="smoke2" time="0.0" classname="testexercise.testng1">
    <ignored/>
  </testcase> <!-- smoke2 -->
</testsuite> <!-- Regression 2 -->
