<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="WKWIN1512713" name="testexercise.testngLoginExamples" tests="6" failures="0" timestamp="14 Feb 2019 13:14:53 GMT" time="4.015" errors="1">
  <testcase name="apiLogin4" time="0.003" classname="testexercise.testngLoginExamples"/>
  <testcase name="apiLogin2" time="0.001" classname="testexercise.testngLoginExamples"/>
  <testcase name="apiLogin1" time="0.000" classname="testexercise.testngLoginExamples"/>
  <testcase name="apiLogin3" time="0.000" classname="testexercise.testngLoginExamples"/>
  <testcase name="mobileLogin" time="4.011" classname="testexercise.testngLoginExamples">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testexercise.testngLoginExamples.mobileLogin() didn&#039;t finish within the time-out 4000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testexercise.testngLoginExamples.mobileLogin() didn't finish within the time-out 4000
at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- mobileLogin -->
  <testcase name="webLogin" classname="testexercise.testngLoginExamples">
    <skipped/>
  </testcase> <!-- webLogin -->
</testsuite> <!-- testexercise.testngLoginExamples -->
